siteTitle="Enact"
baseColor = "#1b5271"
linkPrefix = "/enyojs/enact-docs/1.0.0-alpha.4"
docPages = [
  "/docs/",
  "/docs/components/",
  "/docs/developer-guide/",
  "/docs/developer-resources/",
  "/docs/developer-tools/",
  "/docs/tutorials/"
]
