// @ts-check
import fs from 'fs';
import path from 'path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const docsDir = path.join(process.cwd(), 'docs');
const hasDocsDir = (dirName) => fs.existsSync(path.join(docsDir, dirName));
const mkCategory = (label, dirName) => ({
  type: 'category',
  label,
  items: [{type: 'autogenerated', dirName}],
});

const baseSections = [
  ['Tutorials', 'tutorials'],
  ['Developer Guide', 'developer-guide'],
  ['Developer Tools', 'developer-tools'],
  ['Core', 'core'],
  ['UI', 'ui'],
  ['Spotlight', 'spotlight'],
  ['i18n', 'i18n'],
  ['webOS', 'webos'],
];

const optionalSections = [
  ['Agate', 'agate'],
  ['Limestone', 'limestone'],
  ['Moonstone', 'moonstone'],
  ['Sandstone', 'sandstone'],
];

/** @type {any[]} */
const tutorialSidebar = ['api'];

baseSections.forEach(([label, dirName]) => {
  if (hasDocsDir(dirName)) tutorialSidebar.push(mkCategory(label, dirName));
});
optionalSections.forEach(([label, dirName]) => {
  if (hasDocsDir(dirName)) tutorialSidebar.push(mkCategory(label, dirName));
});

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {tutorialSidebar};

export default sidebars;
