// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Unified docs sidebar: tutorials, developer docs, and API modules.
  tutorialSidebar: [
    'api',
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [{type: 'autogenerated', dirName: 'developer-guide'}],
    },
    {
      type: 'category',
      label: 'Developer Tools',
      items: [{type: 'autogenerated', dirName: 'developer-tools'}],
    },
    {
      type: 'category',
      label: 'Core',
      items: [{type: 'autogenerated', dirName: 'core'}],
    },
    {
      type: 'category',
      label: 'UI',
      items: [{type: 'autogenerated', dirName: 'ui'}],
    },
    {
      type: 'category',
      label: 'Spotlight',
      items: [{type: 'autogenerated', dirName: 'spotlight'}],
    },
    {
      type: 'category',
      label: 'i18n',
      items: [{type: 'autogenerated', dirName: 'i18n'}],
    },
    {
      type: 'category',
      label: 'webOS',
      items: [{type: 'autogenerated', dirName: 'webos'}],
    },
  ],
};

export default sidebars;
